name: basic-ci

on: push

jobs:
  ci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: sb
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: sb
      - uses: actions/checkout@v2
        with:
          repository: friends-library-dev/evans
          path: evans
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: evans
      - name: lint
        run: cd sb && npm run lint
      - name: ts
        run: cd sb && npm run ts:check
      - name: test
        run: cd sb && npm run test
      - name: prettier
        run: cd sb && npm run format -- --check
      - name: build
        run: cd sb && npm run build
